TASK_OBJS = output/myOS/kernel/task/task.o \
			output/myOS/kernel/task/taskQueueFIFO.o	\
			output/myOS/kernel/task/taskPRIO.o	\
			output/myOS/kernel/task/taskarrv.o	\
			output/myOS/kernel/task/taskRR.o	