include $(SRC_RT)/myOS/kernel/mem/Makefile

KERNEL_OBJS = output/myOS/kernel/tick.o \
	      output/myOS/kernel/wallClock.o \
		  output/myOS/kernel/task.o	\
		  output/myOS/kernel/taskQueueFIFO.o \
		  output/myOS/kernel/schedule.o \
	      $(MEM_OBJS)
